# Generated by Django 2.2.6 on 2019-10-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(default='<function uuid4 at 0x0341B150>')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
