# Generated by Django 2.2.6 on 2019-10-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.TextField(default='04641e15-f482-4455-9ba5-b62f2e9b4b65'),
        ),
    ]
